server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Nécessaire pour React Router : redirige toutes les routes vers index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
