/** Catalogue initial des pneus vélo premium Michelin. */
export const TYRE_SEED = [
  // ── ROUTE ──────────────────────────────────────────────────────────────────
  {
    globalId: 'POWER-ROAD-001',
    rangeName: 'POWER',
    modelName: 'POWER ROAD',
    segment: 'Endurance',
    cycleType: 'ROAD',
    cycleTypeWeb: 'ROAD',
    useType: 'ENDURANCE',
    terrainTypes: 'ASPHALT',
    scoreWetGrip: 4,
    scoreRollingResistance: 4,
    scoreDurability: 4,
    scoreTerrainVersatility: 3,
    lifetimeKm: 8000,
    priceRange: '45 – 58 €',
  },
  {
    globalId: 'POWER-ROAD-TLR-001',
    rangeName: 'POWER',
    modelName: 'POWER ROAD TLR',
    segment: 'Endurance',
    cycleType: 'ROAD',
    cycleTypeWeb: 'ROAD',
    useType: 'ENDURANCE TUBELESS',
    terrainTypes: 'ASPHALT',
    scoreWetGrip: 4,
    scoreRollingResistance: 5,
    scoreDurability: 3,
    scoreTerrainVersatility: 3,
    lifetimeKm: 7000,
    priceRange: '50 – 65 €',
  },
  {
    globalId: 'POWER-COMP-001',
    rangeName: 'POWER',
    modelName: 'POWER COMPETITION',
    segment: 'Racing',
    cycleType: 'ROAD',
    cycleTypeWeb: 'ROAD',
    useType: 'RACING',
    terrainTypes: 'ASPHALT',
    scoreWetGrip: 3,
    scoreRollingResistance: 5,
    scoreDurability: 2,
    scoreTerrainVersatility: 2,
    lifetimeKm: 4000,
    priceRange: '55 – 72 €',
  },
  {
    globalId: 'POWER-ALL-SEASON-4S-001',
    rangeName: 'POWER',
    modelName: 'POWER ALL SEASON 4S',
    segment: 'All weather',
    cycleType: 'ROAD',
    cycleTypeWeb: 'ROAD',
    useType: 'ALL WEATHER',
    terrainTypes: 'ASPHALT',
    scoreWetGrip: 5,
    scoreRollingResistance: 3,
    scoreDurability: 4,
    scoreTerrainVersatility: 4,
    lifetimeKm: 9000,
    priceRange: '50 – 65 €',
  },
  {
    globalId: 'POWER-END2-001',
    rangeName: 'POWER',
    modelName: 'POWER ENDURANCE 2',
    segment: 'Endurance',
    cycleType: 'ROAD',
    cycleTypeWeb: 'ROAD',
    useType: 'LONGUE DISTANCE',
    terrainTypes: 'ASPHALT',
    scoreWetGrip: 4,
    scoreRollingResistance: 3,
    scoreDurability: 5,
    scoreTerrainVersatility: 3,
    lifetimeKm: 12000,
    priceRange: '42 – 55 €',
  },
  {
    globalId: 'DYNAMIC-CLASSIC2-001',
    rangeName: 'DYNAMIC',
    modelName: 'DYNAMIC CLASSIC 2',
    segment: 'Entraînement',
    cycleType: 'ROAD',
    cycleTypeWeb: 'ROAD',
    useType: 'ENTRAÎNEMENT',
    terrainTypes: 'ASPHALT',
    scoreWetGrip: 3,
    scoreRollingResistance: 3,
    scoreDurability: 5,
    scoreTerrainVersatility: 3,
    lifetimeKm: 10000,
    priceRange: '32 – 42 €',
  },
  // ── GRAVEL ─────────────────────────────────────────────────────────────────
  {
    globalId: 'POWER-GRAVEL-001',
    rangeName: 'POWER',
    modelName: 'POWER GRAVEL',
    segment: 'Gravel',
    cycleType: 'ROAD',
    cycleTypeWeb: 'GRAVEL',
    useType: 'GRAVEL RACING',
    terrainTypes: 'ASPHALT,OFFROAD HARD PACKED',
    scoreWetGrip: 4,
    scoreRollingResistance: 4,
    scoreDurability: 3,
    scoreTerrainVersatility: 4,
    lifetimeKm: 5000,
    priceRange: '48 – 62 €',
  },
  {
    globalId: 'COUNTRY-ROCK2-001',
    rangeName: 'COUNTRY',
    modelName: 'COUNTRY ROCK 2',
    segment: 'Gravel',
    cycleType: 'ROAD',
    cycleTypeWeb: 'GRAVEL',
    useType: 'AVENTURE GRAVEL',
    terrainTypes: 'ASPHALT,OFFROAD',
    scoreWetGrip: 3,
    scoreRollingResistance: 3,
    scoreDurability: 5,
    scoreTerrainVersatility: 5,
    lifetimeKm: 6000,
    priceRange: '38 – 50 €',
  },
  {
    globalId: 'WILD-CROSS-001',
    rangeName: 'WILD',
    modelName: 'WILD CROSS',
    segment: 'Cyclo-cross',
    cycleType: 'ROAD',
    cycleTypeWeb: 'GRAVEL',
    useType: 'CYCLOCROSS',
    terrainTypes: 'ASPHALT,MUD,OFFROAD',
    scoreWetGrip: 4,
    scoreRollingResistance: 3,
    scoreDurability: 4,
    scoreTerrainVersatility: 5,
    lifetimeKm: 4500,
    priceRange: '40 – 52 €',
  },
  // ── VTT ────────────────────────────────────────────────────────────────────
  {
    globalId: 'WILD-ENDURO-FRONT-001',
    rangeName: 'WILD',
    modelName: 'WILD ENDURO FRONT',
    segment: 'VTT Enduro',
    cycleType: 'MTB',
    cycleTypeWeb: 'MTB',
    fitting: 'FRONT',
    useType: 'ENDURO',
    terrainTypes: 'OFFROAD',
    scoreWetGrip: 5,
    scoreRollingResistance: 2,
    scoreDurability: 4,
    scoreTerrainVersatility: 4,
    lifetimeKm: 3500,
    priceRange: '55 – 72 €',
  },
  {
    globalId: 'WILD-ENDURO-REAR-001',
    rangeName: 'WILD',
    modelName: 'WILD ENDURO REAR',
    segment: 'VTT Enduro',
    cycleType: 'MTB',
    cycleTypeWeb: 'MTB',
    fitting: 'REAR',
    useType: 'ENDURO',
    terrainTypes: 'OFFROAD',
    scoreWetGrip: 4,
    scoreRollingResistance: 3,
    scoreDurability: 5,
    scoreTerrainVersatility: 4,
    lifetimeKm: 2500,
    priceRange: '58 – 75 €',
  },
  {
    globalId: 'WILD-ROCKR2-001',
    rangeName: 'WILD',
    modelName: "WILD ROCK'R 2",
    segment: 'VTT All Mountain',
    cycleType: 'MTB',
    cycleTypeWeb: 'MTB',
    useType: 'ALL MOUNTAIN',
    terrainTypes: 'OFFROAD',
    scoreWetGrip: 4,
    scoreRollingResistance: 3,
    scoreDurability: 4,
    scoreTerrainVersatility: 5,
    lifetimeKm: 3000,
    priceRange: '48 – 65 €',
  },
  {
    globalId: 'FORCE-AM-001',
    rangeName: 'FORCE',
    modelName: 'FORCE AM',
    segment: 'VTT All Mountain',
    cycleType: 'MTB',
    cycleTypeWeb: 'MTB',
    useType: 'ALL MOUNTAIN',
    terrainTypes: 'OFFROAD',
    scoreWetGrip: 4,
    scoreRollingResistance: 3,
    scoreDurability: 4,
    scoreTerrainVersatility: 4,
    lifetimeKm: 3500,
    priceRange: '45 – 60 €',
  },
  {
    globalId: 'WILD-AM2-001',
    rangeName: 'WILD',
    modelName: 'WILD AM 2',
    segment: 'VTT All Mountain',
    cycleType: 'MTB',
    cycleTypeWeb: 'MTB',
    useType: 'ALL MOUNTAIN',
    terrainTypes: 'OFFROAD HARD PACKED,MUD',
    scoreWetGrip: 4,
    scoreRollingResistance: 3,
    scoreDurability: 4,
    scoreTerrainVersatility: 5,
    lifetimeKm: 3000,
    priceRange: '48 – 62 €',
  },
] as const;
